trigger:
- main

resources:
- repo: self

variables:
  IMAGE_NAME: 'darrenchoucn/aca-album-backend-api'
  CONTAINERAPPS_APP: 'ca-cicd-lab-api-dev-ase-001'
  CONTAINERAPPS_ENVIRONMENT: 'acae-cicd-lab-dev-ase-001'
  RESOURCE_GROUP: 'rg-cicd-lab-dev-ase-001'
  TAG: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image to Docker Hub
      inputs:
        containerRegistry: 'docker-hub-connection'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/backend_api/backend_api_csharp/Dockerfile'
        repository: '$(IMAGE_NAME)'
        tags: |
          $(TAG)

- stage: Deploy
  displayName: Deploy to Container Apps
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      displayName: Deploy new container version
      inputs:
        azureSubscription: 'azure-connection'
        imageToDeploy: '$(IMAGE_NAME):$(TAG)'
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '3500'
        ingress: 'external'
